analyzer:
#  depreciated in Dart2
#  strong-mode: true
#   exclude:
#     - path/to/excluded/files/**

# Lint rules and documentation, see http://dart-lang.github.io/linter/lints
linter:
  rules:
    - cancel_subscriptions
    - hash_and_equals
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - test_types_in_equals
    - unrelated_type_equality_checks
    - valid_regexps
    - camel_case_types
# Pana rules
    - prefer_equal_for_default_values
    - avoid_init_to_null
